server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    username: gangnam
    password: gangnam
    url: jdbc:mysql://localhost:3306/login
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  key: adsfiai42@rqn43krn34=adf9%490jtkrnq0daf$nio2mn=as89vhn4     #??? ??? ?? ??(??? ???)
  time: 86400000            #?? ????
